/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
	/**
	 * Client ID of your own start.gg OAuth app. If present alongside startggClientSecret, activates dev mode (direct exchange, no proxy).
	 */
	startggClientId?: string;
	/**
	 * Client Secret of your own start.gg OAuth app.
	 */
	startggClientSecret?: string;
	/**
	 * Client ID of your own Challonge OAuth app. If present alongside challongeClientSecret, activates dev mode.
	 */
	challongeClientId?: string;
	/**
	 * Client Secret of your own Challonge OAuth app.
	 */
	challongeClientSecret?: string;
	/**
	 * Base URL of the packs repository.
	 */
	packsRepoBaseUrl?: string;
	/**
	 * Owner or organization of the packs repository.
	 */
	packsRepoOwner?: string;
	/**
	 * Name of the packs repository.
	 */
	packsRepoName?: string;
	/**
	 * Branch of the packs repository to download assets from.
	 */
	packsRepoBranch?: string;
}
