/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DownloadStates {
	[k: string]: {
		status: 'idle' | 'fetching-manifest' | 'downloading' | 'done' | 'error';
		progress: number;
		error?: string;
		[k: string]: unknown;
	};
}
