/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PackRegistry = {
	schemaVersion: number;
	updatedAt: string;
	packs: {
		id: string;
		name: string;
		gameVersion: string;
		totalSizeBytes: number;
		logoPath: string;
		characterCount: number;
		palette: {
			start: string;
			end: string;
		};
	}[];
} & ({
	schemaVersion: number;
	updatedAt: string;
	packs: {
		id: string;
		name: string;
		gameVersion: string;
		totalSizeBytes: number;
		logoPath: string;
		characterCount: number;
		palette: {
			start: string;
			end: string;
		};
	}[];
} | null);
