/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Scoreboard {
	leftPlayerId: string;
	rightPlayerId: string;
	leftNameOverride: string;
	rightNameOverride: string;
	leftTeamOverride: string;
	rightTeamOverride: string;
	leftCountryOverride: string;
	rightCountryOverride: string;
	leftCharacter: string;
	rightCharacter: string;
	leftScore: number;
	rightScore: number;
	round: string;
	game: string;
	leftBracketStatus: string;
	rightBracketStatus: string;
}
